/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPC_TEST_PROG 0x30000824
#define RPC_TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HELLO 1
extern  int * hello_1(void *, CLIENT *);
extern  int * hello_1_svc(void *, struct svc_req *);
extern int rpc_test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HELLO 1
extern  int * hello_1();
extern  int * hello_1_svc();
extern int rpc_test_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
