#define _POSIX_C_SOURCE		199309L


#include "rpc/rpc.h"
#include "hello.h"



/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>

#include "sys/types.h"
#include "unistd.h"

#include "stdarg.h"
#include "stdint.h"


#include "errno.h"
#include "signal.h"



void func_set_shm_ptr(void * ptr)
{

	uint64_t shm_ptr = 0;

	char * p = (char *)(ptr);

	fprintf(stderr, "[func_get_shm_ptr]: ptr = %p [sizeof(void *) = %d]\n", ptr, sizeof(void *));
	fprintf(stderr, "[func_get_shm_ptr]: shm_ptr = %016X\n", shm_ptr);

	if(ptr)
	{
		fprintf(stderr, "%s", p);


		fprintf(stderr, "\n");

		char tmp_buf[512] = { 0 };
		sprintf(tmp_buf, "%s", p);
		sprintf(p, "[func_get_shm_ptr]: ptr = %p [sizeof(void *) = %d]\n%s", ptr, sizeof(void *), tmp_buf);
	}

	return;

}

struct st_reply
{
	int32_t status;
	char message[512];
};


static int32_t reply_counter = 0;
static struct st_reply reply;

struct st_reply * func_get_reply(void)
{

	return &(reply);

}

int32_t func_get_counter(void)
{
	return reply_counter;
}

int * hello_1_svc(void *a, struct svc_req *req)
{

	reply.status = 1;
	sprintf(reply.message, "reply_counter = %d\n", reply_counter--);

	union sigval value;
	value.sival_int = reply_counter;

	static char msg[256];
//	static char *p;
	static int **p;

	fprintf(stderr, "Parent pid is %d\n", getppid());
	sigqueue(getppid(), SIGRTMIN, value);
	fprintf(stderr, "Getting ready to return value\n");

//	strcpy(msg, "Hello, from RPC server\n");
//	p = msg;

	static int data[4] = { 0xFF, 0, 1, -4 };
	p = data;

	fprintf(stderr, "Return value...\n");

	return (&p);

}


