/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST2_H_RPCGEN
#define _TEST2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPC_TEST_2_PROG 0x30000824
#define RPC_TEST_2_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define F_TEST2 1
extern  char ** f_test2_1(int *, CLIENT *);
extern  char ** f_test2_1_svc(int *, struct svc_req *);
extern int rpc_test_2_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define F_TEST2 1
extern  char ** f_test2_1();
extern  char ** f_test2_1_svc();
extern int rpc_test_2_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST2_H_RPCGEN */
