/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST3_H_RPCGEN
#define _TEST3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int st_rpc_array_len;
	int *st_rpc_array_val;
} st_rpc_array;

#define RPC_TEST_3_PROG 0x30000824
#define RPC_TEST_3_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define F_TEST3 1
extern  char ** f_test3_1(st_rpc_array *, CLIENT *);
extern  char ** f_test3_1_svc(st_rpc_array *, struct svc_req *);
extern int rpc_test_3_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define F_TEST3 1
extern  char ** f_test3_1();
extern  char ** f_test3_1_svc();
extern int rpc_test_3_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_st_rpc_array (XDR *, st_rpc_array*);

#else /* K&R C */
extern bool_t xdr_st_rpc_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST3_H_RPCGEN */
