/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "test3.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

st_rpc_array *
f_test3_1(st_rpc_array *argp, CLIENT *clnt)
{
	static st_rpc_array clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, F_TEST3,
		(xdrproc_t) xdr_st_rpc_array, (caddr_t) argp,
		(xdrproc_t) xdr_st_rpc_array, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
